### ISSUE TITLE
函数名和做圆括号间的空格建议去掉

### ISSUE THREAD

**Issue by helinjiang** [iv-web/eslint-config-ivweb#5]
函数名和做圆括号间的空格必须存在，否则会报错

![image](https://user-images.githubusercontent.com/13464168/48395768-445c4680-e753-11e8-883a-487cf255627c.png)

但这个规则并不合理，原因如下：

- babel 处理过后的文件中，并没有空格
- React 源码中此处也没有空格 https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js
- Google 的[规范](https://zh-google-styleguide.readthedocs.io/en/latest/google-cpp-styleguide/formatting/)中，也推荐不加空格

![image](https://user-images.githubusercontent.com/13464168/48396240-bf722c80-e754-11e8-8240-0bd7d8d443e1.png)

建议将 `space-before-function-paren` 中的 `named` 的值修改为 `never`

修改之前

```
// error; function 的小括号前面必须有空格
    'space-before-function-paren': [2, {
      'anonymous': 'always',
      'named': 'always',
      'asyncArrow': 'always'
    }],
```

建议修改之后

```
// error; function 的小括号前面必须有空格
    'space-before-function-paren': [2, {
      'anonymous': 'always',
      'named': 'never',
      'asyncArrow': 'always'
    }],
```

**Comment by Leo555** [comment]
never 的话直接把这个规则去掉就好了，不用改成 never
